analyze_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("", include('core.urls')),
    path('admin/', admin.site.urls),
]

core/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views
app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('contact/', views.contact, name='contact'),
    path('signup/', views.signup, name='signup'),
    path('login/',views.log_in, name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('forgot-password/', views.forgot_password, name='forgot-password'),
    path('reset-password/<str:uidb64>/<str:token>/', views.reset_password, name='reset-password'),
    path('complete-register/<str:token>/', views.complete_register, name='complete-register')
]

core/models.py
from django.db import models
from django.contrib.auth.models import BaseUserManager, AbstractBaseUser, PermissionsMixin
from django.contrib.postgres.fields import ArrayField

class MyUserManager(BaseUserManager):
    def create_user(self, email, date_of_birth, password=None):
        """
        Creates and saves a User with the given email, date of
        birth and password.
        """
        if not email:
            raise ValueError("Users must have an email address")

        user = self.model(
            email=self.normalize_email(email),
            date_of_birth=date_of_birth,
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, date_of_birth, password=None):
        """
        Creates and saves a superuser with the given email, date of
        birth and password.
        """
        user = self.create_user(
            email,
            password=password,
            date_of_birth=date_of_birth,
        )
        user.is_admin = True
        user.save(using=self._db)
        return user


class MyUser(AbstractBaseUser, PermissionsMixin):
    username=models.CharField(max_length=255,unique=True)
    email=models.EmailField(max_length=255,unique=True)
    password=models.CharField(max_length=255)
    first_name=models.CharField(max_length=255,unique=True, null=True)
    last_name=models.CharField(max_length=255,unique=True, null=True)
    date_of_birth = models.DateField(null=True)
    career = models.TextField(max_length=50, null=True)
    school = models.TextField(max_length=255, null=True)
    cared_industry = ArrayField(
        models.TextField(max_length=50),
        default=list,  # Use a callable (e.g., list) instead of []
        blank=True,
    )
    avatar = models.ImageField(upload_to='avatars/', null=True, blank=True)
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)

    objects = MyUserManager()

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ["date_of_birth"]

    def __str__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        "Does the user have a specific permission?"
        # Simplest possible answer: Yes, always
        return True

    def has_module_perms(self, app_label):
        "Does the user have permissions to view the app `app_label`?"
        # Simplest possible answer: Yes, always
        return True

    @property
    def is_staff(self):
        "Is the user a member of staff?"
        # Simplest possible answer: All admins are staff
        return self.is_admin

core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, PasswordResetForm, SetPasswordForm
from .models import MyUser as User
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _
from django.contrib.auth import password_validation

class LoginForm(AuthenticationForm):
    email = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your Email',
        'class': 'form-input',
        'id': 'txt-input',
        'name': 'email',
        'required': 'true'
    }))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Your password',
        'class': 'form-input',
        'name': 'password',
        'id': 'pwd',
        'required': 'true'
    }))

class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')
    
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your username',
        'class': 'form-input',
        'id': 'txt-input',
        'name': 'username',
        'required': 'true'
    }))
    email = forms.CharField(widget=forms.EmailInput(attrs={
        'placeholder': 'Your email address',
        'class': 'form-input',
        'id': 'txt-input',
        'name': 'email',
        'required': 'true'
    }))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Your password',
        'class': 'form-input',
        'name': 'password',
        'id': 'pwd',
        'required': 'true'
    }))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Repeat password',
        'class': 'form-input',
        'name': 'password',
        'id': 'pwd',
        'required': 'true'
    }))

class CustomPasswordSendEmailForm(PasswordResetForm):
    email = forms.EmailField(
        label=_("Email"),
        required=True,
        widget=forms.EmailInput(attrs={
            'placeholder': 'Your Email',
            'class': 'form-input',
            'id': 'txt-input',
            'name': 'email',
            'required': 'true'
        }),
    )

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if not email:
            raise ValidationError(_('Email field is required'))
        return email
    
class CustomPasswordChangeForm(SetPasswordForm):
    new_password1 = forms.CharField(
        label="New Password",
        widget=forms.PasswordInput(attrs={
            'placeholder': 'New password',
            'class': 'form-input',
            'name': 'password',
            'id': 'pwd',
            'required': 'true'
        }),
        strip=False,
        help_text=password_validation.password_validators_help_text_html(),
    )
    new_password2 = forms.CharField(
        label="Confirm New Password",
        widget=forms.PasswordInput(attrs={
            'placeholder': 'Confirm new password',
            'class': 'form-input',
            'name': 'password',
            'id': 'pwd',
            'required': 'true'
        }),
        strip=False,
        help_text=password_validation.password_validators_help_text_html(),
    )

    def clean_new_password2(self):
        new_password1 = self.cleaned_data.get('new_password1')
        new_password2 = self.cleaned_data.get('new_password2')

        if new_password1 and new_password2 and new_password1 != new_password2:
            raise forms.ValidationError("The two password fields didn't match.")
        
        # Additional custom validation if needed

        return new_password2

core/views.py
from django.shortcuts import render, redirect
from .forms import SignupForm, LoginForm, CustomPasswordChangeForm, CustomPasswordSendEmailForm
from .models import MyUser as User
from django.contrib.auth import authenticate, login
from django.contrib.auth import update_session_auth_hash
from .utils import send_html_email_with_file, create_link_with_token, is_token_valid, decode_token, encode_token
from django.utils.http import urlsafe_base64_decode
from django.contrib import messages
import os
# Create your views here.
def index(request):

    return render(request, 'core/index.html', {
        'categories': [],
        'items': [],
    })

def contact(request):
    return render(request, 'core/contact.html')

def log_in(request):
    if request.user.username != "":
        return redirect('/')

    if request.method == 'POST':
        email = request.POST['email']
        password = request.POST['password']
        
        user = authenticate(request, email=email, password=password)

        if user is not None:
            login(request, user)
            return redirect('/')
        else: 
            form = LoginForm
            return render(request, 'authentication/login.html', {
                'form': form,
                'error_message': 'Email or password is incorrect'
            })
    
    else: 
        form = LoginForm

    return render(request, 'authentication/login.html', {
        'form': form
    })


def signup(request):
    if request.method == 'POST':
        new_user = request.POST
        form = SignupForm(new_user)

        if User.objects.filter(username=new_user['username']).exists() or User.objects.filter(email=new_user['email']).exists():
            # User already exists, handle accordingly (e.g., display an error message)
            return render(request, 'authentication/signup.html', {'form': form, 'error_message': 'User already exists'})
        else:
            if form.is_valid():
                # Create a link assign user information
                new_user.pk = 33
                new_user.is_active = False
                new_user_link = encode_token(new_user, "complete-register")
                # Send is mail for wellcome and validate this email is valid
                to = [new_user['email'],]
                html_file_path = os.getcwd() + '\\core\\templates\\email_template\\welcome.html'
                

                context = {
                    'recipient': new_user['email'], 
                    'new_user_link': new_user_link,
                    'flatform_name': "Mutyses",
                    'flatfrom_number_phone': '0972495038',
                    'flatform_logo': ''
                }
                subject = 'Welcome to new member of flatform'

                sended_email = send_html_email_with_file(subject, to, html_file_path, context)

                if sended_email:
                    
                    return render(request, 'authentication/send-email-result.html', context={"sended": True})
                else:
                    return render(request, 'authentication/send-email-result.html', context={"sended": False})
        

    else:
        form = SignupForm()

    return render(request, 'authentication/signup.html', {
        'form': form
    })
def complete_register(request, token):
    decoded_result = decode_token(token)

    new_user = decoded_result[0]
    form = SignupForm(new_user)
    if form.is_valid():
        form.save()

    return render(request, 'authentication/complete-register.html', {'expired': decoded_result[1]})

def forgot_password(request):
    form = CustomPasswordSendEmailForm()
    try: 


        if request.method == "POST": 
            owner_email = request.POST['email']
            user = User.objects.get(email=owner_email)


            # Create link
            password_reset_link = create_link_with_token(user, "reset-password")

            to = [owner_email,]
            html_file_path = os.getcwd() + '\\core\\templates\\email_template\\reset-password.html'
            context = {
                'recipient': owner_email, 
                'password_reset_link': password_reset_link,
                'flatform_name': "Mutyses",
                'flatfrom_number_phone': '0972495038',
                'flatform_logo': ''
            }
            subject = 'Password Reset'

            send_html_email_with_file(subject, to, html_file_path, context)

            return render(request, 'authentication/send-email-result.html', context={"sended": True})
    except Exception as e:
        print(e)
        return render(request, 'authentication/send-email-result.html', context={"sended": False})



    return render(request, 'authentication/forgot-password.html', {
        'form': form
    })

def reset_password(request, uidb64, token):
    user_id = urlsafe_base64_decode(uidb64).decode()
    user = User.objects.get(pk=user_id)
    checked_expired: bool = is_token_valid(token, user, 300)


    if checked_expired:

        if request.method == 'POST':
            form = CustomPasswordChangeForm(user, request.POST)
            # Remain error when alway not is_valid => 
            print(form.is_valid)
            if form.is_valid():
                user = form.save()
                update_session_auth_hash(request, user)
                messages.success(request, 'Your password was successfully updated!')
                return redirect('/')
            else:
                messages.error(request, 'Please correct the error below.')

        else:
            form = CustomPasswordChangeForm(user)


        return render(request, 'authentication/reset-password.html', {'expired': checked_expired, 'form': form})
    else:
        return render(request, 'authentication/reset-password.html', {'expired': checked_expired})

core/templates/core/base.html
<!doctype html>
{% load static %}
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" integrity="sha512-" crossorigin="anonymous" />
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">
        <link rel="stylesheet" href="{% static 'css/home.css' %}">
        <title>{% block title %}{% endblock %} | Mutyses</title>
    </head>

    <body>
        
        <nav class="navbar navbar-expand-lg home-navbar ">
            <div class="container-fluid">
              <a class="navbar-brand" href="#">Mutyses</a>
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarText">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                  <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="#">Home</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="#">Contact</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">About</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Dashboard</a>
                    </li>
                </ul>

                
                
                <span class="navbar-text">
                    {% if request.user.is_authenticated %}

                        <form action="{% url 'core:logout' %}" class='hover:bg-gray-700' method="post">
                            {% csrf_token %}
                            <button class='btn btn-primary btn-sm' type="submit">Logout</button>
                        </form>
                    {% else %}
                        <a href="{% url 'core:signup' %}" class="home-login sign_up_btn btn btn-primary btn-sm text-white">Sign up</a>
                        <a href="{% url 'core:login' %}" class="home-login btn btn-primary btn-sm text-white">Log in</a>
                    {% endif %}
                </span>
              </div>
            </div>
          </nav>
        
        <div class="px-6 py-6">
            {% block content %}
            {% endblock %}
        </div>

       
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
    </body>
</html>

core/templates/core/contact.html
{% extends 'core/base.html' %}

{% block title %}Contact{% endblock %}

{% block content %}
    <h1>The contact page</h1>
{% endblock %}

core/templates/core/index.html
{% extends 'core/base.html' %}

{% block title %}Welcome{% endblock %}

{% block content %}
    <div class='d-flex justify-content-center mt-5'>
        <form class="d-flex" method="post" action="/analyze">
            <input class="form-control me-2" type="search" placeholder="Type anything..." aria-label="Search">
            <button class="btn btn-outline-success" type="submit">Analyze</button>
          </form>
    </div>
    <h3 class='text-success text-center mt-5'>Information can be found and analyed which is displayed below</h3>
    <div class='d-flex justify-content-center mt-5'>
        
    </div>
{% endblock %}